MIN_BOARD_LENGTH = 3
MIN_BOARD_WIDTH = 3

DEFAULTS_BOARD_LENGTH = 9
DEFAULTS_BOARD_WIDTH = 5

MAX_BOARD_LENGTH = 15
MAX_BOARD_WIDTH = 15

FIRST_COLOR = 'W'
SECOND_COLOR = 'B'
EMPTY_COLOR = 'E'

MOVEMENT_DIAGONAL_LEFT_UP_RIGTH_DOWN = '`|,'
MOVEMENT_UP_DOWN = '|'
MOVEMENT_DIAGONAL_RIGHT_UP_LEFT_DOWN = ',|`'
MOVEMENT_SIDEWAYS = '--'
