MIN_BOARD_LENGTH = 3
MIN_BOARD_WIDTH = 3

DEFAULTS_BOARD_LENGTH = 9
DEFAULTS_BOARD_WIDTH = 5

MAX_BOARD_LENGTH = 15
MAX_BOARD_WIDTH = 15

FIRST_COLOR = 'W'
SECOND_COLOR = 'B'
EMPTY_COLOR = 'E'

MOVEMENT_DIAGONAL_LEFT_UP = 1
MOVEMENT_UP = 2
MOVEMENT_DIAGONAL_RIGHT_UP = 3
MOVEMENT_SIDEWAYS_RIGTH = 4
MOVEMENT_DIAGONAL_RIGTH_DOWN = 5
MOVEMENT_DOWN = 6
MOVEMENT_DIAGONAL_LEFT_DOWN = 7
MOVEMENT_SIDEWAYS_LEFT = 8

CHOICE_WITHDRAWL = 'withdrawl'
CHOICE_APPROACH = 'approach'
